theme: jekyll-theme-cayman
title: Improving Low Compute Language Modeling with In-Domain Embedding Initialisation
description: Code for our EMNLP 2020 Paper
show_downloads: true
google_analytics: UA-19179423-2
